### ISSUE TITLE
 Unable to find installation candidates for milvus-lite (2.4.5)

### ISSUE THREAD

**Issue by nexuewen** [milvus-io/milvus-lite#137]
When I install pymilvus using Poetry, I will be prompted that I cannot find the package of milvus-lite, but I can install it using pip directly, what is the reason?
![image](https://github.com/milvus-io/milvus-lite/assets/1477162/62e5b18e-3515-45ac-bece-e634556e921d)

**Comment by junjiejiangjjj** [comment]
Milvus-lite currently does not support being managed with Poetry.

**Comment by nexuewen** [comment]
> Milvus-lite currently does not support being managed with Poetry.

Do we have a plan to support Poetry?

**Comment by junjiejiangjjj** [comment]
> > Milvus-lite currently does not support being managed with Poetry.
> 
> Do we have a plan to support Poetry?

Yeah, future versions will support it.

**Comment by fsj621** [comment]
I have the same problem. Is there any other way to run milvus in python?

**Comment by junjiejiangjjj** [comment]
> I have the same problem. Is there any other way to run milvus in python?

https://milvus.io/docs/milvus_lite.md

**Comment by junjiejiangjjj** [comment]
![image](https://github.com/milvus-io/milvus-lite/assets/14136703/5aa8182f-514c-46d9-8528-1d4b4f7bc1dc)
Milvus-lite 2.4.8 now supports poetry.
