### ISSUE TITLE
`create_collection` with `collection_name="default"` results in an error

### ISSUE THREAD

**Issue by fzliu** [milvus-io/milvus-lite#148]
![img_v3_02bb_5acddd09-eb66-4703-add1-b93ee5bce46g](https://github.com/milvus-io/milvus-lite/assets/6334158/6b87bedd-1a74-462e-93eb-cd30a5530eaf)
![img_v3_02bb_9a63d6c6-2a31-41bb-b31f-5d4ce6cd432g](https://github.com/milvus-io/milvus-lite/assets/6334158/7eef18e1-ff94-416f-baa3-129e3d440a33)

**Comment by elstic** [comment]
If the collection name is `default`, delete expr reports an error and needs to be fixed.

**Comment by junjiejiangjjj** [comment]
This issue has been resolved in version 2.4.7
