### ISSUE TITLE
can't invoke by server.start()

### ISSUE THREAD

**Issue by Austin-Phoenix** [milvus-io/milvus-lite#185]
debug log as below:
[2024/07/02 17:14:46.181 +08:00] [WARN] [retry/retry.go:39] ["start to reset connection because of specific reasons"] [module=Proxy] [client_role=rootcoord] [error="rpc error: code = Unknown desc = expected=%!s(int64=112), actual=%!s(int64=119): server ID mismatch"]
[2024/07/02 17:14:50.186 +08:00] [WARN] [retry/retry.go:39] ["start to reset connection because of specific reasons"] [module=Proxy] [client_role=rootcoord] [error="rpc error: code = Unknown desc = expected=%!s(int64=112), actual=%!s(int64=119): server ID mismatch"]
[2024/07/02 17:14:58.194 +08:00] [WARN] [retry/retry.go:39] ["start to reset connection because of specific reasons"] [module=Proxy] [client_role=rootcoord] [error="rpc error: code = Unknown desc = expected=%!s(int64=112), actual=%!s(int64=119): server ID mismatch"]
[2024/07/02 17:14:58.195 +08:00] [WARN] [grpcclient/client.go:287] ["retry func failed"] [module=Proxy] ["retry time"=4] [error="rpc error: code = Unknown desc = expected=%!s(int64=112), actual=%!s(int64=119): server ID mismatch"]
[2024/07/02 17:15:08.404 +08:00] [WARN] [retry/retry.go:39] ["start to reset connection because of specific reasons"] [module=Proxy] [client_role=rootcoord] [error="rpc error: code = Unknown desc = expected=%!s(int64=112), actual=%!s(int64=119): server ID mismatch"]
[2024/07/02 17:15:09.425 +08:00] [WARN] [grpcclient/client.go:367] ["fail to get grpc client"] [module=Proxy] [client_role=indexcoord] [error="find no available indexcoord, check indexcoord state"]
[2024/07/02 17:15:09.425 +08:00] [WARN] [retry/retry.go:39] ["grpc client is nil, maybe fail to get client in the retry state"] [module=Proxy] [client_role=indexcoord]
[2024/07/02 17:15:09.425 +08:00] [WARN] [grpcclient/client.go:291] ["fail to get grpc client in the retry state"] [module=Proxy] [client_role=indexcoord] [error="find no available indexcoord, check indexcoord state"]
[2024/07/02 17:15:10.429 +08:00] [WARN] [retry/retry.go:39] ["grpc client is nil, maybe fail to get client in the retry state"] [module=Proxy] [client_role=indexcoord]

**Comment by Austin-Phoenix** [comment]
it seems some service can't start normally. log is :
Traceback (most recent call last):
  File "C:\Users\Austin\PycharmProjects\pythonProject1\RAG1\Milvus\test_milvus.py", line 60, in <module>
    test_check_start()
  File "C:\Users\Austin\PycharmProjects\pythonProject1\RAG1\Milvus\test_milvus.py", line 9, in test_check_start
    debug_server.start()
  File "C:\Users\Austin\PycharmProjects\pythonProject1\.venv\Lib\site-packages\milvus\__init__.py", line 427, in start
    self.wait_started()
  File "C:\Users\Austin\PycharmProjects\pythonProject1\.venv\Lib\site-packages\milvus\__init__.py", line 391, in wait_started
    raise TimeoutError(f'Milvus not startd in {timeout/1000} seconds')
TimeoutError: Milvus not startd in 30.0 seconds

**Comment by xiaofan-luan** [comment]
which milvus lite are u using?
Please try latest milvus lite and it should be much easier to maintain

**Comment by Austin-Phoenix** [comment]
I'm using v2.2.16-lite
I just download by pycharm using: ' pip install milvus -i https://pypi.tuna.tsinghua.edu.cn/simple'. It seems in tsinghua.edu.cn,  it's already latest or best version for my env(my env is under windows 11). But now, it seems works fine after notebook restart.
Anoter question is if i use 'connections.connect(host='127.0.0.1', port=debug_server.listen_port)'. everything is fine.
But when i use 'connections.connect("default", uri="./local_milvus_test.db")', the error shows:
File "C:\Users\Austin\PycharmProjects\pythonProject1\RAG1\Milvus\test_milvus.py", line 121, in test_3
    connections.connect("default", uri="./local_milvus_test.db")
  File "C:\Users\Austin\PycharmProjects\pythonProject1\.venv\Lib\site-packages\pymilvus\orm\connections.py", line 378, in connect
    from milvus_lite.server_manager import server_manager_instance
ModuleNotFoundError: No module named 'milvus_lite'
Something point to source code here:
'from milvus_lite.server_manager import server_manager_instance'
i just used pip to download milvus and pymilvus. Is there something that i missed for milvus_lite
but when i use pip, try to download milvus_lite, it seems there is no module named that, couldn't find it.

**Comment by codingjaguar** [comment]
Hi @Austin-Phoenix, the older version of Milvus Lite <2.4.x is no longer actively maintained. 

Looks like you are using v2.2.16-lite in Windows. The older version is known to have issues like crashing after restarting, due to stability issues. We encourage you to use the latest version of Milvus Lite, which can run on Windows through WSL (https://learn.microsoft.com/en-us/windows/wsl/install). Native windows support is also coming soon, tracked by https://github.com/milvus-io/milvus-lite/issues/176.

Alternatively, you can use the Milvus Standalone mode on Docker, following https://milvus.io/docs/install_standalone-docker.md, which also supports Windows.

**Comment by Austin-Phoenix** [comment]
thanks [codingjaguar](https://github.com/codingjaguar)，i'll try docker for 2.4x milvus version.

**Comment by Austin-Phoenix** [comment]
Dear all,
&nbsp; &nbsp; &nbsp; &nbsp;I already used latest milvus by windows docker desktop.
&nbsp; &nbsp; &nbsp; &nbsp;It seems my&nbsp; docker desktop runs normally.
&nbsp; &nbsp; &nbsp; &nbsp;



Message ID: ***@***.***&gt;

i wand to download latest new milvus, but download failed by following logs:
PS D:\Ubuntu_WSL\Milvus&gt; docker compose up -d
time="2024-07-16T17:56:19+08:00" level=warning msg="D:\\Ubuntu_WSL\\Milvus\\docker-compose.yml: `version` is obsolete"
[+] Running 0/16
&nbsp;- minio [⠀⠀⠀⠀⠀⠀] Pulling&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 146.2s
&nbsp; &nbsp;- c7e856e03741 Retrying in 1 second&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;112.8s
&nbsp; &nbsp;- c1ff217ec952 Retrying in 1 second&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;112.8s
&nbsp; &nbsp;- b12cc8972a67 Retrying in 1 second&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;112.8s
&nbsp; &nbsp;- 4324e307ea00 Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- 152089595ebc Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- 05f217fb8612 Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp;- standalone [⠀⠀⠀⠀⠀⠀⠀⠀] Pulling&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;146.2s
&nbsp; &nbsp;- d5fd17ec1767 Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- ca3a09d8ea0c Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- 838ea2fc0c5a Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- 25e4b36fd223 Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- 5e94f6dcda58 Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- 1f27396f6efc Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- fe556ec02776 Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
&nbsp; &nbsp;- 4f4fb700ef54 Waiting&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 112.8s
error pulling image configuration: download failed after attempts=6: dialing production.cloudflare.docker.com:443 container via direct connection because static system has no HTTPS proxy: connecting to 128.242.240.85:443: dial tcp 128.242.240.85:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Could you&nbsp; please tell me&nbsp; how to resolve this problem?
just configure in docker by this one? i have no idea.......&nbsp; &nbsp;thanks very much.

**Comment by xiaofan-luan** [comment]
> &nbsp; &nbsp;- c7e856e03741 Retrying in 1 second&nbsp; &nbsp;

highly recommend to run milvus on a docker but don't use WSL. we don't have any experience and test on windows system

**Comment by Austin-Phoenix** [comment]
but the root cause is minio and standardalone can't using docker pull successfully.




only etcd can docker pull successfully.

also i download&nbsp;



but it doesn't work.
using&nbsp;
docker pull mbackes/milvus-lite
docker run -d --name milvus -p 3000:80 milvusdb/milvus&nbsp;
so can you tell me if using docker run , how does paramters will&nbsp; be filled? or in 2.4.5 how can i download minio and standardalone component?



can't docker pull with me. only etcd is fine for me
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "milvus-io/milvus-lite"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月16日(星期二) 晚上6:58
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [milvus-io/milvus-lite] can't invoke by server.start() (Issue #185)





  
&nbsp; &nbsp;- c7e856e03741 Retrying in 1 second&nbsp; &nbsp;
  
highly recommend to run milvus on a docker but don't use WSL. we don't have any experience and test on windows system
