### ISSUE TITLE
milvus-server cannot start in macos m1 chip

### ISSUE THREAD

**Issue by LeoMax-Xiong** [milvus-io/milvus-lite#202]
![image](https://github.com/user-attachments/assets/61e41ac8-94ba-4151-b904-a1a45bf88c93)
milvus-lite cannot start in macos m1 chip

**Comment by junjiejiangjjj** [comment]
Hi,  the older version of Milvus Lite <2.4.x is no longer actively maintained. We encourage you to use the latest version of Milvus Lite, which can run on MacOS m1 chip.
