### ISSUE TITLE
是否支持GPU索引部署?

### ISSUE THREAD

**Issue by solemnrole** [milvus-io/milvus-lite#209]
我通过官方文档
https://www.milvus-io.com/getstarted/with_gpu/install_standalone-helm-gpu#%E5%BC%80%E5%A7%8Bmilvus
没有发现milvus如何配置GPU.
"""
# 使用GPU索引时，Milvus将使用内存池来避免频繁的内存分配和释放。
# 在此处，你可以设置内存池占用的内存大小，单位为MB。
# 请注意，当实际内存需求超过maxMemSize设置的值时，Milvus有可能崩溃。
# 如果initMemSize和MaxMemSize都设置为零，
# Milvus将自动初始化可用GPU内存的一半，
# 默认情况下，maxMemSize的值为全部可用的GPU内存。
gpu:
  initMemSize: 0  # 设置初始内存池大小。
  maxMemSize: 0   # maxMemSize设置最大的内存使用限制。当内存使用超过initMemSize时，Milvus将尝试扩展内存池。
"""
我启动后，配置文件并没有这一项目，我添加后也会重新覆盖，是不是不支持GPU呀？

**Comment by codingjaguar** [comment]
Hi! Currently **Milvus Lite** only supports FLAT vector index type on x86 and Mac M1/M2 machines: https://milvus.io/docs/milvus_lite.md.
**Milvus** supports GPU deployment and GPU index. The install instructions: https://milvus.io/docs/prerequisite-gpu.md
