### ISSUE TITLE
MilvusException: <MilvusException:

### ISSUE THREAD

**Issue by tiwari93** [milvus-io/milvus-lite#216]
I am able to connect milvus server with my old dgx server without any issue but unable to do so while on new H100 container in same network. Followed the same code provided on milvus website : https://milvus.io/docs/milvus_lite.md

Cell In[4], line 4
      2 import numpy as np
----> 4 client = MilvusClient("./milvus_demo.db")
      5 client.create_collection(
      6     collection_name="demo_collection",
      7     dimension=384  # The vectors we will use in this demo has 384 dimensions
      8 )

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:60, in MilvusClient.__init__(self, uri, user, password, db_name, token, timeout, **kwargs)
     48 """A client for the common Milvus use case.
     49 
     50 This client attempts to hide away the complexity of using Pymilvus. In a lot ofcases what
   (...)
     58         to None.
     59 """
---> 60 self._using = self._create_connection(
     61     uri, user, password, db_name, token, timeout=timeout, **kwargs
     62 )
     63 self.is_self_hosted = bool(utility.get_server_type(using=self._using) == "milvus")

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:728, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    727     logger.error("Failed to create new connection using: %s", using)
--> 728     raise ex from ex
    729 else:

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:725, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    724 try:
--> 725     connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
    726 except Exception as ex:

File /usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py:449, in Connections.connect(self, alias, user, password, db_name, token, **kwargs)
    447         kwargs["secure"] = True
--> 449 connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
    450 return

File /usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py:400, in Connections.connect.<locals>.connect_milvus(**kwargs)
    398 timeout = t if isinstance(t, (int, float)) else Config.MILVUS_CONN_TIMEOUT
--> 400 gh._wait_for_channel_ready(timeout=timeout)
    401 if kwargs.get("keep_alive", False):

File /usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py:150, in GrpcHandler._wait_for_channel_ready(self, timeout)
    149 except grpc.FutureTimeoutError as e:
--> 150     raise MilvusException(
    151         code=Status.CONNECT_FAILED,
    152         message=f"Fail connecting to server on {self._address}, illegal connection params or server unavailable",
    153     ) from e
    154 except Exception as e:

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on unix:/tmp/tmp7w05_bc6_milvus_demo.db.sock, illegal connection params or server unavailable)>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
    [... skipping hidden 1 frame]

Cell In[4], line 4
      2 import numpy as np
----> 4 client = MilvusClient("./milvus_demo.db")
      5 client.create_collection(
      6     collection_name="demo_collection",
      7     dimension=384  # The vectors we will use in this demo has 384 dimensions
      8 )

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:60, in MilvusClient.__init__(self, uri, user, password, db_name, token, timeout, **kwargs)
     48 """A client for the common Milvus use case.
     49 
     50 This client attempts to hide away the complexity of using Pymilvus. In a lot ofcases what
   (...)
     58         to None.
     59 """
---> 60 self._using = self._create_connection(
     61     uri, user, password, db_name, token, timeout=timeout, **kwargs
     62 )
     63 self.is_self_hosted = bool(utility.get_server_type(using=self._using) == "milvus")

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:728, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    727     logger.error("Failed to create new connection using: %s", using)
--> 728     raise ex from ex
    729 else:

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:725, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    724 try:
--> 725     connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
    726 except Exception as ex:

File /usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py:449, in Connections.connect(self, alias, user, password, db_name, token, **kwargs)
    447         kwargs["secure"] = True
--> 449 connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
    450 return

File /usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py:400, in Connections.connect.<locals>.connect_milvus(**kwargs)
    398 timeout = t if isinstance(t, (int, float)) else Config.MILVUS_CONN_TIMEOUT
--> 400 gh._wait_for_channel_ready(timeout=timeout)
    401 if kwargs.get("keep_alive", False):

File /usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py:150, in GrpcHandler._wait_for_channel_ready(self, timeout)
    149 except grpc.FutureTimeoutError as e:
--> 150     raise MilvusException(
    151         code=Status.CONNECT_FAILED,
    152         message=f"Fail connecting to server on {self._address}, illegal connection params or server unavailable",
    153     ) from e
    154 except Exception as e:

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on unix:/tmp/tmp7w05_bc6_milvus_demo.db.sock, illegal connection params or server unavailable)>

The above exception was the direct cause of the following exception:

MilvusException                           Traceback (most recent call last)
Cell In[4], line 4
      1 from pymilvus import MilvusClient
      2 import numpy as np
----> 4 client = MilvusClient("./milvus_demo.db")
      5 client.create_collection(
      6     collection_name="demo_collection",
      7     dimension=384  # The vectors we will use in this demo has 384 dimensions
      8 )

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:60, in MilvusClient.__init__(self, uri, user, password, db_name, token, timeout, **kwargs)
     38 def __init__(
     39     self,
     40     uri: str = "http://localhost:19530",
   (...)
     46     **kwargs,
     47 ) -> None:
     48     """A client for the common Milvus use case.
     49 
     50     This client attempts to hide away the complexity of using Pymilvus. In a lot ofcases what
   (...)
     58             to None.
     59     """
---> 60     self._using = self._create_connection(
     61         uri, user, password, db_name, token, timeout=timeout, **kwargs
     62     )
     63     self.is_self_hosted = bool(utility.get_server_type(using=self._using) == "milvus")

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:728, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    726 except Exception as ex:
    727     logger.error("Failed to create new connection using: %s", using)
--> 728     raise ex from ex
    729 else:
    730     logger.debug("Created new connection using: %s", using)

File /usr/local/lib/python3.10/dist-packages/pymilvus/milvus_client/milvus_client.py:725, in MilvusClient._create_connection(self, uri, user, password, db_name, token, **kwargs)
    723 using = uuid4().hex
    724 try:
--> 725     connections.connect(using, user, password, db_name, token, uri=uri, **kwargs)
    726 except Exception as ex:
    727     logger.error("Failed to create new connection using: %s", using)

File /usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py:449, in Connections.connect(self, alias, user, password, db_name, token, **kwargs)
    446         if parsed_uri.scheme == "https":
    447             kwargs["secure"] = True
--> 449     connect_milvus(**kwargs, user=user, password=password, token=token, db_name=db_name)
    450     return
    452 # 2nd Priority, connection configs from env

File /usr/local/lib/python3.10/dist-packages/pymilvus/orm/connections.py:400, in Connections.connect.<locals>.connect_milvus(**kwargs)
    397 t = kwargs.get("timeout")
    398 timeout = t if isinstance(t, (int, float)) else Config.MILVUS_CONN_TIMEOUT
--> 400 gh._wait_for_channel_ready(timeout=timeout)
    401 if kwargs.get("keep_alive", False):
    402     gh.register_state_change_callback(
    403         ReconnectHandler(self, alias, kwargs_copy).reconnect_on_idle
    404     )

File /usr/local/lib/python3.10/dist-packages/pymilvus/client/grpc_handler.py:150, in GrpcHandler._wait_for_channel_ready(self, timeout)
    148     self._setup_identifier_interceptor(self._user, timeout=timeout)
    149 except grpc.FutureTimeoutError as e:
--> 150     raise MilvusException(
    151         code=Status.CONNECT_FAILED,
    152         message=f"Fail connecting to server on {self._address}, illegal connection params or server unavailable",
    153     ) from e
    154 except Exception as e:
    155     raise e from e

MilvusException: <MilvusException: (code=2, message=Fail connecting to server on unix:/tmp/tmp7w05_bc6_milvus_demo.db.sock, illegal connection params or server unavailable)>

**Comment by junjiejiangjjj** [comment]
hi @ tiwari93, what system are you using? Currently, milvus-lite only supports
Ubuntu >= 20.04 (x86_64 and arm64)
MacOS >= 11.0 (Apple Silicon M1/M2 and x86_64)

**Comment by tiwari93** [comment]
I am using ubantu 22.04, details are given below:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"

**Comment by tiwari93** [comment]
I found the root cause for the error. Its due to restricted access to the path where I was trying to save the db.
