### ISSUE TITLE
[Bug]: client.close() doesn't remove .db.lock file

### ISSUE THREAD

**Issue by jaewon-ju** [milvus-io/milvus-lite#227]
In Milvus Lite, the db.lock file is not removed after calling client.close(), which leads to an error message indicating "the file has been opened by another program" when attempting to reopen the database file.

--- 

### Steps to Reproduce

Call `client.close()`
Attempt to access `path/to/db/coding.db` after closure.
Observe the error: coding.db failed, the file has been opened by another program.

---

### Expected Behavior
The db.lock file should be automatically deleted when client.close() is called, allowing subsequent access to the database without issues.

---

## Environment

Milvus Lite Version: 2.4.10
OS: macOS
Python Version: 3.11.5

---

### Additional Context
The presence of an undeleted db.lock file prevents further access to the database file, causing operational issues during execution.

**Comment by junjiejiangjjj** [comment]
hi @jaewon-ju , the lock is released when the process exits. The client in the same process can open the db file multiple times. The lock file is to prevent different processes from opening the db file at the same time.

**Comment by jaewon-ju** [comment]
hi @junjiejiangjjj , thank you for your answer!
I thought that lock will be deleted when the connection is disconnected.
