### ISSUE TITLE
Build error in arm64

### ISSUE THREAD

**Issue by Amphetaminewei** [milvus-io/milvus-lite#237]
Hi, I'm having the following issue compiling milvus lite on an arm machine:

/home/wangweinan/prj/milvus-lite/build/thirdparty/milvus/internal/core/thirdparty/knowhere/knowhere-src/src/simd/distances_neon.cc:23:27: error: ‘vld1q_f32_x4’ was not declared in this scope; did you mean ‘vld1q_f32_x2’?
   23 |         float32x4x4_t a = vld1q_f32_x4(x + dim - d);
      |                           ^~~~~~~~~~~~
      |                           vld1q_f32_x2
/home/wangweinan/prj/milvus-lite/build/thirdparty/milvus/internal/core/thirdparty/knowhere/knowhere-src/src/simd/distances_neon.cc: In function ‘float faiss::fvec_L2sqr_neon(const float*, const float*, size_t)’:
/home/wangweinan/prj/milvus-lite/build/thirdparty/milvus/internal/core/thirdparty/knowhere/knowhere-src/src/simd/distances_neon.cc:90:27: error: ‘vld1q_f32_x4’ was not declared in this scope; did you mean ‘vld1q_f32_x2’?
   90 |         float32x4x4_t a = vld1q_f32_x4(x + dim - d);
      |                           ^~~~~~~~~~~~
      |                           vld1q_f32_x2

I took a look at the local header file /usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h, which only defines vld1q_f32_x2 and vld1q_f32_x3, and no vld1q_f32_x4.

Is my instruction set version too low?
If you don't compile the distances_neon.cc file, will there be any impact?

**Comment by junjiejiangjjj** [comment]
hi @Amphetaminewei , milvus-lite can be compiled using gcc11

**Comment by Amphetaminewei** [comment]
@junjiejiangjjj I only have gcc9 and gcc10 on my source, I'll see if I can compile on gcc10.

**Comment by Amphetaminewei** [comment]
I checked that the gcc10 header file has this definition, let me try it

**Comment by Amphetaminewei** [comment]
Hi @junjiejiangjjj ,After switching to gcc10, this error was resolved.

After solving this problem, I waited here for more than 20 minutes with no change in progress:
```
[ 55%] Built target tantivy_binding_target
    Building [=======================> ] 245/247: opendal-c(build)
```
And my CPU usage is not high, is there something wrong with the compilation?
