### ISSUE TITLE
Milvus-lite 2.4.11 doesn't install on macos

### ISSUE THREAD

**Issue by eavanvalkenburg** [milvus-io/milvus-lite#242]
2.4.10 does install, but 2.4.11 does not!

**Comment by junjiejiangjjj** [comment]
hi @eavanvalkenburg , please wait a moment, today we only released the MacOS x86_64 package, and the M chip version will be released later today.

**Comment by eavanvalkenburg** [comment]
ah I see it is there now, thanks for checking in, is there a way for you guys to release in one go?

**Comment by codingjaguar** [comment]
Yep in the future we will release all pkgs of milvus lite in one go

**Comment by eavanvalkenburg** [comment]
Thanks!
