### ISSUE TITLE
It will be better to add some prompts for successful startup when the milvus server starts.

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/milvus-lite#45]
Now when we use the "milvus-server" command to start milvus, there is no prompt on the terminal that the startup is successful.
![image](https://user-images.githubusercontent.com/53512883/231429958-0c5419e1-01b1-4cec-a343-a046b49764ea.png)

It will be better to add some prompts for successful startup when the milvus server starts. Just like starting jupyter.
![image](https://user-images.githubusercontent.com/53512883/231430241-217ec649-07e9-4b7e-8f5a-9f60b85653b0.png)

**Comment by matrixji** [comment]
Try to add banner output in v2.2.6
