### ISSUE TITLE
milvus.before() not running

### ISSUE THREAD

**Issue by arrrrny** [milvus-io/milvus-lite#85]
I successfully installed the milvus package 
Installing collected packages: milvus
Successfully installed milvus-2.3.5

Created the data folder and then run below to start embedded milvus on my mac Intel and having error

python3
Python 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import milvus
>>> milvus.before()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'milvus' has no attribute 'before'
>>>

**Comment by matrixji** [comment]
I don't think the `milvus` has the attribute or method `before`, where is the reference for this code `milvus.before()`?

**Comment by arrrrny** [comment]
This came up on google search and maybe should be removed for not causing confusion.
https://milvus.io/docs/v2.1.x/install_embedded_milvus.md

I installed via docker and all is fine
